<script setup>
import { inject, onMounted, ref } from 'vue'
import { call } from './api.js'
const session = inject('session'), settings = ref(null), search = ref(''), results = ref([]), busy = ref(false), error = ref(''), message = ref('')
async function load() { try { settings.value = await call('storefront.settings') } catch (e) { error.value = e.message } }
async function find() { busy.value = true; error.value = ''; try { results.value = (await call('orders.search_products', { search: search.value })).items } catch (e) { error.value = e.message } finally { busy.value = false } }
function select(item) { if (!settings.value.products.some(row => row.item === item.item)) settings.value.products.push({ item: item.item, item_name: item.item_name }) }
async function save() { busy.value = true; error.value = ''; message.value = ''; try { settings.value = await call('storefront.configure', { mode: settings.value.mode, title: settings.value.title, random_count: settings.value.random_count, products: settings.value.products.map(item => item.item) }, true); message.value = 'Public store updated.' } catch (e) { error.value = e.message } finally { busy.value = false } }
onMounted(() => { if (session.value.platform_admin) load() })
</script>
<template>
  <section class="store-page storefront-settings"><RouterLink to="/store">← Public store</RouterLink><h1>Storefront products</h1><p class="muted">Choose the products customers see above the shop directory.</p><p v-if="!session.platform_admin" class="lc-notice">Platform administrator access is required.</p><p v-if="error" role="alert" class="lc-notice">{{ error }}</p><p v-if="message" role="status" class="success-note">{{ message }}</p><form v-if="settings" class="lc-form" @submit.prevent="save"><fieldset :disabled="busy"><label>Display mode<select v-model="settings.mode"><option>Disabled</option><option>Selected</option><option>Random</option></select></label><label>Section title<input v-model="settings.title" maxlength="80" required></label><label v-if="settings.mode === 'Random'">Number of random products<input v-model.number="settings.random_count" type="number" min="1" max="24" required><small>A new selection is shown when the store is opened or refreshed.</small></label><template v-if="settings.mode === 'Selected'"><label>Find products<input v-model="search" type="search" maxlength="140" placeholder="Search by product name"></label><button type="button" :disabled="search.trim().length < 2" @click="find">Search products</button><div class="featured-selection"><article v-for="item in results" :key="item.item"><img v-if="item.image" :src="item.image" :alt="item.item_name"><div><strong>{{ item.item_name }}</strong><small>{{ item.shop_name }}</small></div><button type="button" :disabled="settings.products.length >= 24 || settings.products.some(row => row.item === item.item)" @click="select(item)">Select</button></article></div><h3>Selected products · {{ settings.products.length }}/24</h3><p class="muted">Products appear in the order you select them.</p><div class="featured-selection"><article v-for="item in settings.products" :key="item.item"><strong>{{ item.item_name }}</strong><button type="button" @click="settings.products = settings.products.filter(row => row.item !== item.item)">Remove</button></article></div></template><button type="submit" class="lc-primary">{{ busy ? 'Saving…' : 'Save public store' }}</button></fieldset></form></section>
</template>
